Update installation.md, consolidate Fedora infos
containers/podman.io_old pull request #302
Opened 2020-10-21 12:07 UTC by frederik-b

Consolidated infos for Fedora and CentOS which appeared twice.

2020-10-21 20:48 UTC, TomSweeneyRedHat commented on getting-started/installation.md
> -repository before it goes out to all Fedora users.
I would like to keep this line still, but move it to 289.5, just below where you moved the first line here.

2020-10-21 20:49 UTC, TomSweeneyRedHat commented on getting-started/installation.md
> +You can test the very latest Podman in Fedora's `updates-testing`.
```suggestion
You can test the very latest Podman in Fedora's `updates-testing`
repository before it goes out to all Fedora users.
```

2020-10-21 20:50 UTC, TomSweeneyRedHat commented on getting-started/installation.md
>  #### Fedora
```suggestion
#### [Fedora](https://www.fedoraproject.org)
```

2020-10-21 20:55 UTC, TomSweeneyRedHat commented
@lsm5 PTAL

2020-11-04 16:48 UTC, nasirhm requested changes
Nice work on it.

2020-11-04 16:48 UTC, nasirhm commented on getting-started/installation.md
> +sudo yum -y install podman
`sudo dnf install -y podman` as [dnf](https://en.wikipedia.org/wiki/DNF_(software)) is the default package manager for Fedora.

2020-11-04 17:00 UTC, lsm5 commented
@frederik-b could you rebase please?

2020-12-22 14:14 UTC, rhatdan commented
Most of this is already fixed. Closing.

2020-12-22 14:14 UTC, closed without merging