Added rootless container to host networking in the docs
containers/podman.io_old pull request #393
Opened 2021-05-03 19:48 UTC by afro-coder

Hi,

Please correct me if I'm doing this incorrectly, I'm new to this.
Pull request will fix https://github.com/containers/podman/issues/10180 

Regards,
Leon.

2021-05-03 20:15 UTC, rhatdan commented
LGTM
@AkihiroSuda @TomSweeneyRedHat PTAL

2021-05-03 20:17 UTC, AkihiroSuda requested changes
Doesn't seem correct

2021-05-03 20:17 UTC, AkihiroSuda commented on getting-started/network.md
> +To allow connections to the host machine from within your container.
This is not needed for connecting to the host using its real IP (e.g. 192.168.42.100).

This is only needed for connecting to the host via slirp4netns virtual router 10.0.2.2.

2021-05-03 20:22 UTC, TomSweeneyRedHat commented
@afro-coder TYVM for the contribution.  Can you touch this up per @AkihiroSuda suggestion?  

Two small things for future reference.  The change that you did in `_config.yml` is only necessary if you're going to post a blog post to the site.  We'd be delighted if you did that at some point, so no need to adjust that now.

Secondly, when you're putting a PR together that's addressing an issue, have this in your description:

`Fixes: #{issuenumber}` 

That way when the PR is merged the issue gets closed automagically.

2021-05-04 05:33 UTC, afro-coder commented on getting-started/network.md
> +To allow connections to the host machine from within your container.
Hi, thank you for the correction, so should it be this.

To allow connections to the host machine from within your container.
```suggestion
To allow connections to slirp4netns virtual router(10.0.2.2) the from within your container.
```
This is also highlighted in the issue, the docs should clarify this. This is correct right?
```**Note**: Host_IP_Address here is the IP address of your host machine(laptop, VM)```

If these are correct I can edit it and submit a new pull request. Thanks.

2021-05-04 05:43 UTC, afro-coder commented
Hey @TomSweeneyRedHat no problem I want to help in anyway I can, thank you for creating the opportunity to do so, its somewhat my first open source contribution.

I hopefully can write an article someday, I haven't checked out the blog completely but these seem to be quite in-depth and new, the only thing I can probably write about is building podman from source. 

About the `Fixes: #{issuenumber}` I'm a bit confused since the issue is linked to the podman repo, is it possible to link the issue or should I rather create a new issue in podman.io repo and add a reference to the podman repo issue.

Any pointers would do as I couldn't find any syntax online.

2021-05-04 17:53 UTC, akostadinov commented on getting-started/network.md
> +To allow connections to the host machine from within your container.
In the linked issue I read that root-full containers use bridge network by default and this is for rootless only. Perhaps document both situations.

2021-05-04 21:55 UTC, TomSweeneyRedHat commented
@afro-coder Ooops, missed the salient point that the issue was in Podman's repo, not this one.  

I've just changed the line in your description: 

`Pull request will fix containers/podman#10180`

to 

`Fixes: containers/podman#10180` 

and I think GitHub will autoclose it for you.

2021-05-05 14:48 UTC, afro-coder commented on getting-started/network.md
> +To allow connections to the host machine from within your container.
@akostadinov let me try to replicate this on my machine so I can add this to the docs to, need some clarity on the network part as the differences in bridge and normal network are sort off confusing me, waiting for @AkihiroSuda to approve the previous lines, In the meanwhile I'll try to run podman on different network types.

2021-05-05 14:49 UTC, afro-coder commented
> @afro-coder Ooops, missed the salient point that the issue was in Podman's repo, not this one.
> 
> I've just changed the line in your description:
> 
> `Pull request will fix containers/podman#10180`
> 
> to
> 
> `Fixes: containers/podman#10180`
> 
> and I think GitHub will autoclose it for you.

Thank you!

2021-05-20 10:50 UTC, afro-coder commented on getting-started/network.md
> +To allow connections to the host machine from within your container.
@akostadinov hi I have sort of updated the documentation in the pull request, I'm not very proficient with git, learning it myself, but are you able to see the new changes? And can you tell me if this is something that would be helpful? Thanks.

2021-05-20 16:34 UTC, akostadinov commented on getting-started/network.md
> +To allow connections to slirp4netns virtual router(10.0.2.2) the from within your container.
I would suggest a rewording of the above, something like:

> For rootless containers, `slirp4netns` network type is used by default. In such case `Host_IP_Address` should be the address of the slirp4netns virtual router (10.0.2.2). Also command line option `--net slirp4netns:allow_host_loopback=true` needs to be added because local connections are not permitted by default.

I think the additional command below is not needed.

2021-05-24 13:00 UTC, afro-coder commented on getting-started/network.md
> +To allow connections to slirp4netns virtual router(10.0.2.2) the from within your container.
Hey @akostadinov that's not true, you can do connections back to your host via the IP address, just not the virtual router IP 10.0.2.2, even I was a bit confused by this.

For example, Host IP here is my VM's IP address 192.168.31.45
I have another container running

```console
podman run --rm -dit --name webserver1 -p8081:80,8082:443 -v quay.io/libpod/banner

06772c7dc799  quay.io/libpod/banner  nginx -g daemon o...  5 hours ago  Up 5 hours ago  0.0.0.0:8081->80/tcp, 0.0.0.0:8082->443/tcp  webserver1
```
Now let me run your container( I'm not entirely sure of your use case here) but I did a lot of tests
```console
podman run --name porxy --rm --add-host=host.docker.internal:10.0.2.2 -p 3008:3008 -ti --entrypoint /bin/bash quay.io/openshift/origin-cli:4.6
```
```console
[root@80fbbb60f2c5 /]# ip r
default via 10.0.2.2 dev tap0 
10.0.2.0/24 dev tap0 proto kernel scope link src 10.0.2.100 
```
```console
curl 192.168.31.45:8081
   ___          __              
  / _ \___  ___/ /_ _  ___ ____ 
 / ___/ _ \/ _  /  ' \/ _ `/ _ \
/_/   \___/\_,_/_/_/_/\_,_/_//_/
```
Also have you made a connection between Rootful containers and rootless containers I'm trying to run a Haproxy container as rootfull and a simple static website as a rootless container, but I can't access it without using the gateway IP or the VM IP any idea how would I use a domain name to do the same?

2021-05-25 04:15 UTC, akostadinov commented on getting-started/network.md
> +To allow connections to slirp4netns virtual router(10.0.2.2) the from within your container.
The slirp4netns virtual router (10.0.2.2) is connecting to localhost (127.0.0.1). While any other host address does not seem to be protected in this way. So if we have a service bound to all host IPS (like `-p` option without IP specified), then other IPs would be usable. If one specifies `-p=127.0.0.1:lport:cport`, then connecting to other IPs will not work.

This might be totally the desired behavior. It is just not clear for a user that didn't dig deep in the matter. For me the unexpected behavior is that `-plport:cport` makes port available on `0.0.0.0`. Maybe this is for compatibility with Docker and I'm fine with this. Just I didn't expect it.

2021-05-25 16:01 UTC, afro-coder commented on getting-started/network.md
> +To allow connections to slirp4netns virtual router(10.0.2.2) the from within your container.
Hi, but isn't it the same with docker? If you do not specify any ipaddress in `run -p8080:80` by default it is listening on all interfaces.
I tried checking this too. Here I'm running a rootless docker.

Also rootless docker command its using slirp4netns and also has disabled `--disable-host-loopback` 
by default
```console
/user.slice/user-1000.slice/user@1000.service/docker.service
           ├─40635 rootlesskit --net=slirp4netns --mtu=65520 --slirp4netns-sandbox=auto --slirp4netns-seccomp=auto --disable-host-loopback --port-driver=builtin --copy-up=/etc --copy-up=/run --propagation=rslave /usr/bin/dockerd-rootless.sh
           ├─40657 /proc/self/exe --net=slirp4netns --mtu=65520 --slirp4netns-sandbox=auto --slirp4netns-seccomp=auto --disable-host-loopback --port-driver=builtin --copy-up=/etc --copy-up=/run --propagation=rslave /usr/bin/dockerd-rootless.sh
           ├─40673 slirp4netns --mtu 65520 -r 3 --disable-host-loopback --enable-sandbox --enable-seccomp 40657 tap0
```

```console
$ docker run -d -p 8080:80 quay.io/libpod/banner
dcee8f292b23c736cb9e14d3e20e0753aef92cdb5bc970963a1b59bf2c814bf2
$ docker ps
CONTAINER ID   IMAGE                   COMMAND                  CREATED          STATUS         PORTS                                   NAMES
dcee8f292b23   quay.io/libpod/banner   "nginx -g 'daemon of…"   11 seconds ago   Up 9 seconds   0.0.0.0:8080->80/tcp, :::8080->80/tcp   reverent_elgamal

$ ss -patun
ss -patun
Netid       State          Recv-Q       Send-Q                     Local Address:Port                Peer Address:Port                                                       
tcp         LISTEN         0            128                              0.0.0.0:8080                     0.0.0.0:*            users:(("rootlesskit",pid=40635,fd=10))       
tcp         LISTEN         0            128                                 [::]:8080                        [::]:*            users:(("rootlesskit",pid=40635,fd=13))
```
Now I'll run it the same way but this time I'll give 127.0.0.1 as the IP.
```console
$ docker run -d -p 127.0.0.1:8081:80 quay.io/libpod/banner
86fe229b64ded32ef74b805ea65248624c56ea5401bd08555a38096ae1846273

$ docker ps
CONTAINER ID   IMAGE                   COMMAND                  CREATED             STATUS             PORTS                                   NAMES
86fe229b64de   quay.io/libpod/banner   "nginx -g 'daemon of…"   7 seconds ago       Up 5 seconds       127.0.0.1:8081->80/tcp                  friendly_leakey
dcee8f292b23   quay.io/libpod/banner   "nginx -g 'daemon of…"   About an hour ago   Up About an hour   0.0.0.0:8080->80/tcp, :::8080->80/tcp   reverent_elgamal


$ ss -patun| grep "8080\|8081"
tcp    LISTEN  0       128                    0.0.0.0:8080        0.0.0.0:*      users:(("rootlesskit",pid=40635,fd=10))                                        
tcp    LISTEN  0       128                  127.0.0.1:8081        0.0.0.0:*      users:(("rootlesskit",pid=40635,fd=15))                                        
tcp    LISTEN  0       128                       [::]:8080           [::]:*      users:(("rootlesskit",pid=40635,fd=13))  
 ```
This works the same, the `-p $IP:localport:containerport` always works this way because you can either choose to run your containers locally on `127.0.0.1` or you can expose them to your network on `0.0.0.0`

Let me know if you're talking about something other than this, I'm also sort of new to containers but I've been fidgeting with them.

2021-05-25 19:22 UTC, akostadinov commented on getting-started/network.md
> +To allow connections to slirp4netns virtual router(10.0.2.2) the from within your container.
I don't know how it is in Docker, I've never been a docker user. My assumption is that podman follows docker behavior. 

Let me try to clarify my concern, I'm trying to say that it's better to have this behavior documented. Podman is a separate project, while it provides compatibility with Docker, it might be the only project people have worked with and referring to docker docs to learn podman is not optimal IMO.

2021-05-25 23:57 UTC, TomSweeneyRedHat commented on getting-started/network.md
> +To allow connections to slirp4netns virtual router(10.0.2.2) the from within your container.
@akostadinov great conversation, and it's probably late night brain on my part, but I'm not totally clear what change you'd like to see at this point.  Is the change OK to post now in your opinion or do you have a suggested change to the working @afro-coder has?

Also, FWIW, Podman does try to emulate Docker's behavior in most cases.  A few fringe cases where it doesn't make sense or they have new functionality, but this is not one of those cases.

2021-05-26 07:14 UTC, akostadinov commented on getting-started/network.md
> +To allow connections to slirp4netns virtual router(10.0.2.2) the from within your container.
@TomSweeneyRedHat , similar to  my earlier suggestion, maybe something along the lines of:
> For rootless containers, slirp4netns network type is used by default. In such case Host_IP_Address should be an IP address of the host machine (but not 127.0.0.1).
> In case 127.0.0.1 of host machine needs to be accessed, then it should be IP address of slirp4netns virtual router (10.0.2.2) and command line option --net slirp4netns:allow_host_loopback=true needs to be added because localhost connections are not permitted by default.

Also would be useful to mention somewhere above that with the `-p` option, the port is bound to all IPs of host machine as this is IMO non-intuitive for new users (even though this is the docker behavior, this doesn't mean only docker experts will be using podman).

Does this make sense?

2021-05-27 11:35 UTC, afro-coder commented on getting-started/network.md
> +To allow connections to slirp4netns virtual router(10.0.2.2) the from within your container.
This seems doable, I'll add it tomorrow or so, @TomSweeneyRedHat would you like to add anything to this?

P.S I added some clarity below so that new users can understand it too, I get that now since as a new user a lot of things would be confusing, even I directly started with podman so I understand how confusing it can get, I'll try to add examples showing these differences too.

> @TomSweeneyRedHat , similar to my earlier suggestion, maybe something along the lines of:
> 
> > For rootless containers, slirp4netns network type is used by default. In such case Host_IP_Address should be an IP address of the host machine (**but not the loopback interface** 127.0.0.1).
> > In case 127.0.0.1 of host machine needs to be accessed, then it should be IP address of slirp4netns virtual router (10.0.2.2) and command line option --net slirp4netns:allow_host_loopback=true needs to be added because **localhost connections are not permitted by default due to security reasons.**
> 
> Also would be useful to mention somewhere above that with the `-p` option, the port is bound to all IPs of host machine as this is IMO non-intuitive for new users (even though this is the docker behavior, this doesn't mean only docker experts will be using podman).
> 
> Does this make sense?

2021-05-27 18:07 UTC, TomSweeneyRedHat commented on getting-started/network.md
> +To allow connections to slirp4netns virtual router(10.0.2.2) the from within your container.
LGTM in general, @rhatdan any further thoughts on your end?

2021-05-27 18:21 UTC, rhatdan commented on getting-started/network.md
> +To allow connections to slirp4netns virtual router(10.0.2.2) the from within your container.
SGTM

2021-05-28 14:00 UTC, afro-coder commented on getting-started/network.md
> +To allow connections to slirp4netns virtual router(10.0.2.2) the from within your container.
Oh okay so we can go ahead with this? Then I can work on this further in the meantime too, simplifying the documentation so that even beginners can easily understand. @akostadinov if you're okay with this, we can also collaborate after this merge so that I can get your views on how the material is for the next merge or something like that.

2021-05-28 15:20 UTC, akostadinov commented on getting-started/network.md
> +To allow connections to slirp4netns virtual router(10.0.2.2) the from within your container.
It's alright. I express my views but my issue is already resolved and I'm not in a hurry. Feel free to do a you see fit.

2021-05-30 11:17 UTC, merged

2021-06-04 10:31 UTC, afro-coder commented
I just noticed a typo in that merge and I'm wondering if it can be done directly or if I would need to push the code to the branch.

```
To allow connections to slirp4netns virtual router(10.0.2.2) the from within your container.
```
Should be
```
To allow connections to **the** slirp4netns virtual router(10.0.2.2) from within your container.
```
I apologize for missing that.

2021-06-07 12:52 UTC, rhatdan commented
Please open another PR to fix this.