Update master to main in links
containers/podman.io_old pull request #402
Opened 2021-05-13 20:01 UTC by TomSweeneyRedHat

Update a number of links through out the site to
fix the master to main merge.

Fixes: https://github.com/containers/podman/issues/10330

Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

2021-05-13 20:09 UTC, lsm5 approved these changes
LGTM, I guess this will need a followup once podman and c/common itself does the branch rename.

2021-05-13 20:11 UTC, lsm5 commented
err, hang on..

2021-05-13 20:12 UTC, lsm5 commented
@TomSweeneyRedHat if we're s/master/main/g to `podman` links, I think there's a few other files that need changes.

```
Index File               Line Content
    0 CODE-OF-CONDUCT.md    3 The podman.io project follows the [Containers Community Code of Conduct](https://github.com/containers/common/blob/master/CODE-OF-CONDUCT.md).
    1 README.md            98 To be more inclusive, the `master` branch for this repository has been renamed to `main`.  If you have a local clone, you can update it by running:
    2 README.md           101 git branch -m master main
    3 SECURITY.md           3 The podman.io Project follows the [Security and Disclosure Information Policy](https://github.com/containers/common/blob/master/SECURITY.md) for the Containers Projects.
    4 releases/index.md    10 ### Release Notes on [GitHub](https://github.com/containers/podman/blob/master/RELEASE_NOTES.md)
    5 whatis.md            17 The Podman service runs only on Linux platforms, however the podman remote REST API client exists on Mac and Windows platforms and can communicate with the Podman service running on a Linux machine or VM via ssh. [Mac client](https://github.com/containers/podman/blob/master/docs/tutorials/>
```

2021-05-13 20:18 UTC, TomSweeneyRedHat commented
@lsm5 the first four need to stay at the moment, but I'll get the last two, thanks!

2021-05-13 20:33 UTC, lsm5 commented on getting-started/installation.md
> +#### Man Page: [registries.conf.5](https://github.com/containers/image/blob/main/docs/containers-registries.conf.5.md)
i'm quite certain this will be a dead link since we don't have c/image `main` branch yet. Same comment for many other links.

2021-05-13 20:39 UTC, TomSweeneyRedHat commented
Chatting with @lsm5 in IRC, the best approach for this PR is to hold it until Podman also converts as many of the references here are in the Podman repository and will die until that repository is converted too.

2021-05-13 20:44 UTC, lsm5 requested changes

2021-05-13 20:44 UTC, lsm5 commented on getting-started/installation.md
> +#### Man Page: [policy.json.5](https://github.com/containers/image/blob/main/docs/containers-policy.json.5.md)
link not ready yet.

2021-05-13 20:44 UTC, lsm5 commented on whatis.md
> +*   Supporting `docker swarm`. We believe that Kubernetes is the defacto standard for composing Pods and for orchestrating containers, making Kubernetes YAML a defacto standard file format. Hence, Po
link not ready yet.

2021-05-13 20:44 UTC, lsm5 commented on _posts/2018-12-12-podman-alpha-v0.12.1.1.md
> +To see the full changelog, please visit our release notes on [GitHub](https://github.com/containers/podman/blob/main/RELEASE_NOTES.md)
not ready

2021-05-13 20:44 UTC, lsm5 commented on _posts/2019-01-16-podman-release-v1.0.0.md
> +You can find instructions for installing Podman [here](https://github.com/containers/podman/blob/main/install.md)
not ready

2021-05-13 20:44 UTC, lsm5 commented on _posts/2019-01-16-podman-release-v1.0.0.md
> +As always, please visit our release notes on [GitHub](https://github.com/containers/podman/blob/main/RELEASE_NOTES.md) to see the full changelog.
not ready

2021-05-13 20:44 UTC, lsm5 commented on _posts/2018-08-15-python-support-for-podman.md
> +[https://github.com/containers/podman/tree/main/contrib/python](https://github.com/containers/podman/tree/main/contrib/python)
not ready

2021-05-13 20:44 UTC, lsm5 commented on _posts/2019-01-16-podman-varlink.md
> +the rendered [API.md](https://github.com/containers/podman/blob/main/API.md).
not ready

2021-05-13 20:44 UTC, lsm5 commented on _posts/2019-01-16-podman-varlink.md
> +the rendered [API.md](https://github.com/containers/podman/blob/main/API.md).
not ready

2021-05-13 20:44 UTC, lsm5 commented on _posts/2019-01-16-podman-varlink.md
> +the rendered [API.md](https://github.com/containers/podman/blob/main/API.md).
not ready

2021-05-13 20:44 UTC, lsm5 commented on _posts/2019-02-26-podman-release-v1.1.0.md
> +You can find instructions for installing Podman [here](https://github.com/containers/podman/blob/main/install.md)
not ready

2021-05-13 20:44 UTC, lsm5 commented on _posts/2019-02-26-podman-release-v1.1.0.md
> +As always, please visit our release notes on [GitHub](https://github.com/containers/podman/blob/main/RELEASE_NOTES.md) to see the full changelog.
not ready

2021-05-13 20:44 UTC, lsm5 commented on _posts/2019-03-01-podman-release-v1.1.1.md
> +As always, please visit our release notes on [GitHub](https://github.com/containers/podman/blob/main/RELEASE_NOTES.md) to see the full changelog.
not ready

2021-05-13 20:44 UTC, lsm5 commented on _posts/2019-03-01-podman-release-v1.1.1.md
> +You can find instructions for installing Podman [here](https://github.com/containers/podman/blob/main/install.md)
not ready

2021-05-13 20:44 UTC, lsm5 commented on _posts/2019-05-10-podman-release-v1.3.0.md
> +As always, please visit our release notes on [GitHub](https://github.com/containers/podman/blob/main/RELEASE_NOTES.md) to see the full changelog.
not ready

2021-05-13 20:44 UTC, lsm5 commented on _posts/2019-05-10-podman-release-v1.3.0.md
> +You can find instructions for installing Podman [here](https://github.com/containers/podman/blob/main/install.md)
not ready

2021-05-13 20:44 UTC, lsm5 commented on _posts/2019-08-14-podman-release-v1.5.0.md
> +As always, please visit our release notes on [GitHub](https://github.com/containers/podman/blob/main/RELEASE_NOTES.md) to see the full changelog.
not ready

2021-05-13 20:44 UTC, lsm5 commented on _posts/2019-08-14-podman-release-v1.5.0.md
> +You can find instructions for installing Podman [here](https://github.com/containers/podman/blob/main/install.md).
not ready

2021-05-13 20:44 UTC, lsm5 commented on _posts/2019-09-26-podman-in-hpc.md
> +The following is a simple MPI based example taken from Open MPI: [ring.c](https://raw.githubusercontent.com/open-mpi/ompi/main/orte/test/mpi/ring.c)
not ready

2021-05-13 20:44 UTC, lsm5 commented on _posts/2019-10-15-generate-seccomp-profiles.md
> +We implemented the syscall tracer as an Open Container Initiative (OCI) [runtime hook](https://github.com/opencontainers/runtime-spec/blob/main/config.md#posix-platform-hooks). OCI runtime hooks are
not ready

2021-05-13 20:44 UTC, lsm5 commented on _posts/2019-10-29-podman-crun-f31.md
> +Now  I’m going to follow the steps in the [Basic Setup and Use of Podman in a Rootless environments](https://github.com/containers/podman/blob/main/docs/tutorials/rootless_tutorial.md) tutorial to do
not ready

2021-05-13 20:44 UTC, lsm5 commented on _posts/2020-01-08-podman-release-v1.7.0.md
> +You can find instructions for installing Podman [here](https://github.com/containers/podman/blob/main/install.md).
not ready

2021-05-13 20:44 UTC, lsm5 commented on _posts/2020-01-08-podman-release-v1.7.0.md
> +As always, please visit our page on [GitHub](https://github.com/containers/podman/blob/main/RELEASE_NOTES.md) to see the full changelog.
not ready

2021-05-13 20:44 UTC, lsm5 commented on _posts/2020-04-17-podman-release-v1.9.0.md
> +The `containers.conf` configuration file (documentation [here](https://github.com/containers/common/blob/main/docs/containers.conf.5.md)) is the eventual replacement for our old configuration file, `
not ready

2021-05-13 20:44 UTC, lsm5 commented on _posts/2020-08-17-work-the-problems.md
> +That's been a helpful creed for me and it's also helpful for the Podman world too.  Many times the community spends a fair amount of effort answering issues and questions either in GitHub's [issues](
not ready

2021-05-13 20:44 UTC, lsm5 commented on _posts/2020-12-11-remove-varlink-libpod-conf-notice.md
> +At the same time as the removal of the Podman v1.0 API, the `libpod.conf` file has also been removed and it too will no longer be included with Podman starting in Podman v3.0.  The functionality of t
not ready

2021-05-13 20:44 UTC, lsm5 commented on _posts/2021-02-08-easy-development-dependency-management-with-podman-and-tent.md
> +But `mysql` is not the only available service. A list of all the available services can be found on: [services.go](https://github.com/fhsinchy/tent/blob/main/store/services.go)
not ready

2021-05-13 20:44 UTC, lsm5 commented on community/meeting/notes/2020-12-01/index.md
> +See [API tests using python requests library](https://github.com/containers/podman/tree/main/test/apiv2/rest_api) for examples.
not ready

2021-05-13 20:44 UTC, lsm5 commented on community/meeting/notes/2021-02-02/index.md
> +Podman 3.0 will be the largest ever.  Expecting an RC3 later this week, 3.0 final by Wednesday of next week.  Docker Compose support is a large one, along with podman rename.  Copy support for remote
not ready

2021-05-13 20:44 UTC, lsm5 commented on community/meeting/notes/2021-02-02/index.md
> +Release notes for v3.0:[here](https://github.com/containers/podman/blob/main/RELEASE_NOTES.md)
not ready

2021-05-13 20:44 UTC, lsm5 commented on community/meeting/notes/2021-02-02/index.md
> +FYI, release notes for 3.0 live at https://github.com/containers/podman/blob/main/RELEASE_NOTES.md
not ready

2021-05-13 20:44 UTC, lsm5 commented on community/meeting/notes/2021-04-06/index.md
> +Matt pulled up the release notes (https://github.com/containers/podman/blob/main/RELEASE_NOTES.md).  Matt likes to get rleases out every 6 to 8 weeks
not ready

2021-05-13 20:44 UTC, lsm5 commented on getting-started/index.md
> +Please also reference the [Podman Troubleshooting Guide](https://github.com/containers/podman/blob/main/troubleshooting.md)
not ready

2021-05-13 20:44 UTC, lsm5 commented on getting-started/index.md
> +[README.md](https://github.com/containers/podman/blob/main/test/README.md).
not ready

2021-05-13 20:44 UTC, lsm5 commented on getting-started/index.md
> +on the [README.md](https://github.com/containers/podman/blob/main/commands.md)
not ready

2021-05-13 20:44 UTC, lsm5 commented on getting-started/installation.md
> +If you have problems when running Podman in  [rootless](https://github.com/containers/podman/blob/main/README.md#rootless) mode follow the instructions [here](https://wiki.archlinux.org/index.php/Lin
not ready

2021-05-13 20:44 UTC, lsm5 commented on getting-started/installation.md
> +A proper description of setting up CNI networking is given in the [`cni` README](https://github.com/containers/podman/blob/main/cni/README.md).
not ready

2021-06-30 16:07 UTC, rhatdan commented
Replaced by #426

2021-06-30 16:07 UTC, closed without merging