Add Aug 2021 Cabal Notes
containers/podman.io_old pull request #440
Opened 2021-08-25 00:29 UTC by TomSweeneyRedHat

Add the meeting notes from the August 2021 Podman Community
Cabal Meeting.

Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

2021-08-26 14:02 UTC, lsm5 requested changes
some comments, but mostly LGTM.

2021-08-26 14:02 UTC, lsm5 commented on community/meeting/notes/2021-08-19/index.md
> +#### Podman on Widows (12:30 in the video)
Windows, unless there's a new OS :)

2021-08-26 14:02 UTC, lsm5 commented on community/meeting/notes/2021-08-19/index.md
> +Fedora costs $10 for Fedora 34 distribution from the Microsoft Store.
woah, is that like a 1-time fee?

2021-08-26 14:02 UTC, lsm5 commented on community/meeting/notes/2021-08-19/index.md
> +When's Podman v3.3 coming out?  Hopefully Monday, Aug 23, 2021.  Then we will likely be creating a Podman 3.4 for sometime later in the fall.
Do we need to update this with current info?

2021-08-26 14:02 UTC, lsm5 commented on community/meeting/notes/2021-08-19/index.md
> +One thing to watch is that Podman v4.0 can not break Fedora 35.  Fedora 36 should be in April 2022 and would be the target if we break Fedora 35, but that's hopefully won't be the case.
but that* hopefully

2021-08-28 18:42 UTC, TomSweeneyRedHat commented on community/meeting/notes/2021-08-19/index.md
> +When's Podman v3.3 coming out?  Hopefully Monday, Aug 23, 2021.  Then we will likely be creating a Podman 3.4 for sometime later in the fall.
No, I think it represented our knowledge at the time.

2021-08-28 18:45 UTC, TomSweeneyRedHat commented on community/meeting/notes/2021-08-19/index.md
> +Fedora costs $10 for Fedora 34 distribution from the Microsoft Store.
Actually, $9.99 + tax, or $10.61 in my case, and yes, one time cost.  I'm not sure if it's one time per machine or per account....

2021-08-28 18:46 UTC, TomSweeneyRedHat commented on community/meeting/notes/2021-08-19/index.md
> +#### Podman on Widows (12:30 in the video)
tweaked.

2021-08-28 18:58 UTC, TomSweeneyRedHat commented on community/meeting/notes/2021-08-19/index.md
> +One thing to watch is that Podman v4.0 can not break Fedora 35.  Fedora 36 should be in April 2022 and would be the target if we break Fedora 35, but that's hopefully won't be the case.
fixed

2021-08-28 21:11 UTC, merged